apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-manifests
  labels:
    app: nginx-manifests
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx-manifests
  template:
    metadata:
      labels:
        app: nginx-manifests
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-manifests
  labels:
    app: nginx-manifests
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-manifests
